"""Generate local grammar content files for v1."""

from __future__ import annotations

import hashlib
import json
import random
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1] / "content" / "grammar"


def shuffled_options(topic_id: str, exercise_key: str, options: list[str]) -> list[str]:
    seed_source = f"{topic_id}:{exercise_key}".encode("utf-8")
    seed = int(hashlib.md5(seed_source).hexdigest()[:8], 16)
    rng = random.Random(seed)
    result = list(options)
    rng.shuffle(result)
    return result


TOPICS_BY_LEVEL = {
    "a1": [
        {
            "topic_id": "to_be",
            "title": "To Be",
            "summary": "Use am, is, are to describe identity, age, location, and basic states.",
            "structure": ["I am", "You/We/They are", "He/She/It is"],
            "examples": ["I am happy.", "She is a teacher.", "They are at home."],
            "common_mistakes": ["Using is with I.", "Omitting the verb in short sentences.", "Confusing are and is."],
            "mc_gap_pairs": [
                ("I ___ happy today.", "am", ["is", "are", "be"]),
                ("She ___ my sister.", "is", ["am", "are", "be"]),
                ("They ___ at school.", "are", ["is", "am", "be"]),
                ("We ___ ready now.", "are", ["is", "am", "be"]),
                ("He ___ from Spain.", "is", ["am", "are", "be"]),
                ("You ___ very kind.", "are", ["is", "am", "be"]),
                ("The cat ___ under the table.", "is", ["am", "are", "be"]),
                ("I ___ not late.", "am", ["is", "are", "be"]),
            ],
            "transformations": [
                ("He is my friend.", "Rewrite using 'is not'.", "He is not my friend."),
                ("They are in the office.", "Rewrite as a negative sentence.", "They are not in the office."),
                ("She is tired.", "Rewrite as a question.", "Is she tired?"),
                ("You are ready.", "Rewrite as a question.", "Are you ready?"),
            ],
            "mistake_type": "to_be_form",
        },
        {
            "topic_id": "articles_a_an_the",
            "title": "Articles A/An/The",
            "summary": "Use a/an for singular non-specific nouns and the for specific things already known.",
            "structure": ["a + consonant sound", "an + vowel sound", "the + specific noun"],
            "examples": ["I saw a dog.", "She bought an apple.", "The book on the table is mine."],
            "common_mistakes": ["Using a before a vowel sound.", "Missing the with specific nouns.", "Using the for general plural nouns."],
            "mc_gap_pairs": [
                ("I have ___ car.", "a", ["an", "the", "-"]),
                ("She ate ___ orange.", "an", ["a", "the", "-"]),
                ("___ sun is hot.", "the", ["a", "an", "-"]),
                ("He is ___ doctor.", "a", ["an", "the", "-"]),
                ("We need ___ umbrella.", "an", ["a", "the", "-"]),
                ("Please close ___ door.", "the", ["a", "an", "-"]),
                ("It is ___ useful idea.", "a", ["an", "the", "-"]),
                ("Can you pass me ___ salt?", "the", ["a", "an", "-"]),
            ],
            "transformations": [
                ("I saw apple.", "Rewrite with the correct article.", "I saw an apple."),
                ("She is teacher.", "Rewrite with the correct article.", "She is a teacher."),
                ("Sun is bright.", "Rewrite with the correct article.", "The sun is bright."),
                ("He bought umbrella.", "Rewrite with the correct article.", "He bought an umbrella."),
            ],
            "mistake_type": "article_use",
        },
        {
            "topic_id": "present_simple",
            "title": "Present Simple",
            "summary": "Use Present Simple for routines, repeated actions, and general facts.",
            "structure": ["I/You/We/They + base verb", "He/She/It + verb-s"],
            "examples": ["I work every day.", "She goes to school by bus.", "They live in Madrid."],
            "common_mistakes": ["Missing -s with he/she/it.", "Using Present Continuous for routines.", "Forgetting do/does in questions."],
            "mc_gap_pairs": [
                ("She ___ to school every day.", "goes", ["go", "going", "gone"]),
                ("They ___ coffee in the morning.", "drink", ["drinks", "drinking", "drank"]),
                ("He ___ tennis on Sundays.", "plays", ["play", "playing", "played"]),
                ("I ___ my homework after dinner.", "do", ["does", "doing", "did"]),
                ("My brother ___ in London.", "lives", ["live", "living", "lived"]),
                ("We ___ English at school.", "study", ["studies", "studying", "studied"]),
                ("Anna ___ TV in the evening.", "watches", ["watch", "watching", "watched"]),
                ("You ___ very fast.", "run", ["runs", "running", "ran"]),
            ],
            "transformations": [
                ("She goes to work by bus.", "Rewrite as a negative sentence.", "She does not go to work by bus."),
                ("They play football on Fridays.", "Rewrite as a negative sentence.", "They do not play football on Fridays."),
                ("He works at home.", "Rewrite as a question.", "Does he work at home?"),
                ("You like coffee.", "Rewrite as a question.", "Do you like coffee?"),
            ],
            "mistake_type": "subject_verb_agreement",
        },
        {
            "topic_id": "there_is_are",
            "title": "There Is / There Are",
            "summary": "Use there is for singular nouns and there are for plural nouns when introducing things.",
            "structure": ["There is + singular noun", "There are + plural noun"],
            "examples": ["There is a book on the desk.", "There are two cats in the garden.", "There is some milk in the fridge."],
            "common_mistakes": ["Using there is with plural nouns.", "Using there are with singular nouns.", "Forgetting article a/an with singular countable nouns."],
            "mc_gap_pairs": [
                ("There ___ a book on the table.", "is", ["are", "be", "am"]),
                ("There ___ many students here.", "are", ["is", "be", "am"]),
                ("There ___ an apple in my bag.", "is", ["are", "be", "am"]),
                ("There ___ two windows in the room.", "are", ["is", "be", "am"]),
                ("There ___ some water in the bottle.", "is", ["are", "be", "am"]),
                ("There ___ three cars outside.", "are", ["is", "be", "am"]),
                ("There ___ a cat under the chair.", "is", ["are", "be", "am"]),
                ("There ___ a lot of people at the party.", "are", ["is", "be", "am"]),
            ],
            "transformations": [
                ("A book is on the desk.", "Rewrite using there is.", "There is a book on the desk."),
                ("Two dogs are in the yard.", "Rewrite using there are.", "There are two dogs in the yard."),
                ("There is a bank near here.", "Rewrite as a question.", "Is there a bank near here?"),
                ("There are many chairs in the room.", "Rewrite as a question.", "Are there many chairs in the room?"),
            ],
            "mistake_type": "there_is_are",
        },
    ],
    "a2": [
        {
            "topic_id": "past_simple",
            "title": "Past Simple",
            "summary": "Use Past Simple for completed actions in the past.",
            "structure": ["Regular verbs: verb-ed", "Questions/negatives: did + base verb"],
            "examples": ["I visited Rome last year.", "She watched a film yesterday.", "Did you call him?"],
            "common_mistakes": ["Using past form after did.", "Forgetting -ed on regular verbs.", "Mixing present and past time markers."],
            "mc_gap_pairs": [
                ("We ___ a film last night.", "watched", ["watch", "watches", "watching"]),
                ("She ___ to Paris in June.", "travelled", ["travel", "travels", "travelling"]),
                ("I ___ my keys yesterday.", "lost", ["lose", "loses", "losing"]),
                ("They ___ tennis after school.", "played", ["play", "plays", "playing"]),
                ("He ___ dinner at 7 p.m.", "cooked", ["cook", "cooks", "cooking"]),
                ("You ___ me last week.", "helped", ["help", "helps", "helping"]),
                ("Anna ___ her homework at home.", "did", ["do", "does", "doing"]),
                ("My dad ___ the car on Sunday.", "washed", ["wash", "washes", "washing"]),
            ],
            "transformations": [
                ("She watched TV yesterday.", "Rewrite as a negative sentence.", "She did not watch TV yesterday."),
                ("They played basketball last Friday.", "Rewrite as a question.", "Did they play basketball last Friday?"),
                ("He visited his aunt.", "Rewrite as a negative sentence.", "He did not visit his aunt."),
                ("You cleaned the room.", "Rewrite as a question.", "Did you clean the room?"),
            ],
            "mistake_type": "past_simple_form",
        },
        {
            "topic_id": "present_continuous",
            "title": "Present Continuous",
            "summary": "Use Present Continuous for actions happening now or around now.",
            "structure": ["am/is/are + verb-ing"],
            "examples": ["I am reading now.", "She is talking on the phone.", "They are studying today."],
            "common_mistakes": ["Forgetting the verb to be.", "Using base verb instead of -ing form.", "Using Present Simple for actions happening now."],
            "mc_gap_pairs": [
                ("He ___ a book now.", "is reading", ["reads", "read", "reading"]),
                ("They ___ dinner at the moment.", "are cooking", ["cook", "cooks", "cooking"]),
                ("I ___ to music right now.", "am listening", ["listen", "listens", "listening"]),
                ("She ___ on the phone.", "is talking", ["talks", "talk", "talking"]),
                ("We ___ for the test today.", "are studying", ["study", "studies", "studying"]),
                ("My dog ___ on the sofa.", "is sleeping", ["sleeps", "sleep", "sleeping"]),
                ("You ___ very fast today.", "are working", ["work", "works", "working"]),
                ("The children ___ in the garden.", "are playing", ["play", "plays", "playing"]),
            ],
            "transformations": [
                ("She is watching TV.", "Rewrite as a negative sentence.", "She is not watching TV."),
                ("They are studying now.", "Rewrite as a question.", "Are they studying now?"),
                ("I am cooking dinner.", "Rewrite as a negative sentence.", "I am not cooking dinner."),
                ("He is running in the park.", "Rewrite as a question.", "Is he running in the park?"),
            ],
            "mistake_type": "present_continuous_form",
        },
        {
            "topic_id": "comparatives_superlatives",
            "title": "Comparatives and Superlatives",
            "summary": "Use comparatives to compare two things and superlatives for the extreme in a group.",
            "structure": ["short adj + -er / the -est", "more / the most + long adjective"],
            "examples": ["My car is faster than yours.", "This is the tallest building here.", "English is more useful than I expected."],
            "common_mistakes": ["Using more with short adjectives.", "Missing than in comparatives.", "Forgetting the in superlatives."],
            "mc_gap_pairs": [
                ("This book is ___ than that one.", "better", ["good", "best", "more good"]),
                ("Anna is the ___ student in the class.", "tallest", ["taller", "more tall", "tall"]),
                ("My bag is ___ than yours.", "heavier", ["heavy", "heaviest", "more heavy"]),
                ("It is the ___ film I know.", "most interesting", ["more interesting", "interesting", "interestinger"]),
                ("Today is ___ than yesterday.", "colder", ["coldest", "more cold", "cold"]),
                ("This exercise is the ___ one.", "easiest", ["easier", "more easy", "easy"]),
                ("Your idea is ___ than mine.", "more practical", ["practicaler", "practical", "most practical"]),
                ("That was the ___ day of my week.", "worst", ["worse", "bad", "more bad"]),
            ],
            "transformations": [
                ("My house is big. Your house is bigger.", "Rewrite as one sentence with than.", "Your house is bigger than my house."),
                ("This test is easy. That test is easier.", "Rewrite as one sentence with than.", "That test is easier than this test."),
                ("Mount Everest is high.", "Rewrite using the superlative form.", "Mount Everest is the highest."),
                ("This is a useful app.", "Rewrite using the superlative form.", "This is the most useful app."),
            ],
            "mistake_type": "comparison_form",
        },
        {
            "topic_id": "future_will_going_to",
            "title": "Future with Will / Going To",
            "summary": "Use will for spontaneous decisions and predictions, and be going to for plans or evidence-based predictions.",
            "structure": ["will + base verb", "am/is/are going to + base verb"],
            "examples": ["I will help you.", "She is going to study medicine.", "It is going to rain."],
            "common_mistakes": ["Using will and going to with the wrong context.", "Forgetting the verb be before going to.", "Using verb-ing after will."],
            "mc_gap_pairs": [
                ("Look at the clouds. It ___ rain.", "is going to", ["will", "going", "is"]),
                ("I forgot my bag. I ___ go back.", "will", ["am going to", "going", "will to"]),
                ("She ___ visit her aunt next weekend.", "is going to", ["will", "going", "is"]),
                ("Don’t worry. I ___ help you.", "will", ["am going to", "going", "will to"]),
                ("They bought tickets. They ___ travel tomorrow.", "are going to", ["will", "going", "are"]),
                ("I think you ___ like this film.", "will", ["are going to", "going", "will to"]),
                ("We ___ move house next month.", "are going to", ["will", "going", "are"]),
                ("The phone is ringing. I ___ answer it.", "will", ["am going to", "going", "will to"]),
            ],
            "transformations": [
                ("She plans to study tonight.", "Rewrite using going to.", "She is going to study tonight."),
                ("I decided now to call him.", "Rewrite using will.", "I will call him."),
                ("They are going to buy a car.", "Rewrite as a negative sentence.", "They are not going to buy a car."),
                ("He will help us.", "Rewrite as a question.", "Will he help us?"),
            ],
            "mistake_type": "future_form_choice",
        },
    ],
    "b1": [
        {
            "topic_id": "present_perfect",
            "title": "Present Perfect",
            "summary": "Use Present Perfect for life experience and actions connected to the present.",
            "structure": ["have/has + past participle"],
            "examples": ["I have visited Rome.", "She has finished her homework.", "They have lived here for years."],
            "common_mistakes": ["Using past time markers like yesterday.", "Using have with he/she/it.", "Using past simple instead of past participle."],
            "mc_gap_pairs": [
                ("She ___ finished her work.", "has", ["have", "had", "is"]),
                ("I ___ never seen this film.", "have", ["has", "had", "am"]),
                ("They ___ lived here for years.", "have", ["has", "had", "are"]),
                ("He ___ already done it.", "has", ["have", "had", "is"]),
                ("We ___ just arrived.", "have", ["has", "had", "are"]),
                ("Anna ___ broken her phone.", "has", ["have", "had", "is"]),
                ("You ___ met him before.", "have", ["has", "had", "are"]),
                ("My parents ___ gone out.", "have", ["has", "had", "are"]),
            ],
            "transformations": [
                ("I visited London before.", "Rewrite in Present Perfect.", "I have visited London before."),
                ("She finished her homework.", "Rewrite in Present Perfect.", "She has finished her homework."),
                ("They have seen this film.", "Rewrite as a negative sentence.", "They have not seen this film."),
                ("He has called you.", "Rewrite as a question.", "Has he called you?"),
            ],
            "mistake_type": "present_perfect_form",
        },
        {
            "topic_id": "first_conditional",
            "title": "First Conditional",
            "summary": "Use the first conditional for real future possibilities.",
            "structure": ["If + present simple, will + base verb", "will + base verb if + present simple"],
            "examples": ["If it rains, we will stay home.", "I will call you if I am late.", "If she studies, she will pass."],
            "common_mistakes": ["Using will in the if-clause.", "Using present simple in both clauses when talking about future results.", "Forgetting comma when the if-clause comes first."],
            "mc_gap_pairs": [
                ("If it rains, we ___ at home.", "will stay", ["stay", "stays", "will stays"]),
                ("She will pass if she ___ hard.", "studies", ["will study", "study", "studied"]),
                ("If I ___ late, I will text you.", "am", ["will be", "be", "was"]),
                ("They will buy the house if the bank ___ yes.", "says", ["will say", "say", "said"]),
                ("If you hurry, you ___ the bus.", "will catch", ["catch", "catches", "will catches"]),
                ("We will go outside if the sun ___.", "shines", ["will shine", "shine", "shined"]),
                ("If he ___ enough money, he will travel.", "saves", ["will save", "save", "saved"]),
                ("I will cook dinner if you ___ home early.", "come", ["will come", "comes", "came"]),
            ],
            "transformations": [
                ("Study hard or you will fail.", "Rewrite using if.", "If you study hard, you will not fail."),
                ("I will call you if I am free.", "Rewrite with the if-clause first.", "If I am free, I will call you."),
                ("If she is tired, she will rest.", "Rewrite as a negative result.", "If she is tired, she will not work."),
                ("We will stay home if it rains.", "Rewrite with the if-clause first.", "If it rains, we will stay home."),
            ],
            "mistake_type": "conditional_form",
        },
        {
            "topic_id": "gerund_vs_infinitive",
            "title": "Gerund vs Infinitive",
            "summary": "Some verbs are followed by gerunds, some by infinitives, and some can take both with a change in meaning.",
            "structure": ["enjoy + verb-ing", "want + to + verb", "decide + to + verb"],
            "examples": ["I enjoy reading.", "She wants to leave.", "They decided to stay."],
            "common_mistakes": ["Using to after enjoy.", "Using -ing after want.", "Mixing patterns after common verbs."],
            "mc_gap_pairs": [
                ("I enjoy ___ books.", "reading", ["to read", "read", "reads"]),
                ("She wants ___ early.", "to leave", ["leaving", "leave", "left"]),
                ("They decided ___ at home.", "to stay", ["staying", "stay", "stayed"]),
                ("He hates ___ late.", "being", ["to be", "be", "is"]),
                ("We hope ___ you soon.", "to see", ["seeing", "see", "saw"]),
                ("Anna loves ___ in the sea.", "swimming", ["to swim", "swim", "swam"]),
                ("I need ___ my room.", "to clean", ["cleaning", "clean", "cleaned"]),
                ("He finished ___ the report.", "writing", ["to write", "write", "wrote"]),
            ],
            "transformations": [
                ("I enjoy to read novels.", "Rewrite correctly.", "I enjoy reading novels."),
                ("She wants going home.", "Rewrite correctly.", "She wants to go home."),
                ("They decided staying here.", "Rewrite correctly.", "They decided to stay here."),
                ("He finished to write the email.", "Rewrite correctly.", "He finished writing the email."),
            ],
            "mistake_type": "verb_pattern",
        },
        {
            "topic_id": "basic_passive",
            "title": "Basic Passive",
            "summary": "Use the passive when the action is more important than the doer.",
            "structure": ["be + past participle", "The letter was sent yesterday."],
            "examples": ["English is spoken here.", "The cake was made yesterday.", "The room is cleaned every day."],
            "common_mistakes": ["Using active word order.", "Forgetting the correct form of be.", "Using base verb instead of past participle."],
            "mc_gap_pairs": [
                ("English ___ here.", "is spoken", ["speaks", "is speak", "spoken"]),
                ("The cake ___ yesterday.", "was made", ["made", "was make", "is made"]),
                ("The room ___ every day.", "is cleaned", ["cleans", "is clean", "cleaned"]),
                ("Cars ___ in this factory.", "are produced", ["produce", "are produce", "produced"]),
                ("The letters ___ this morning.", "were sent", ["sent", "were send", "are sent"]),
                ("Rice ___ in many countries.", "is grown", ["grows", "is grow", "grown"]),
                ("The house ___ in 1990.", "was built", ["built", "was build", "is built"]),
                ("The windows ___ once a week.", "are washed", ["wash", "are wash", "washed"]),
            ],
            "transformations": [
                ("People speak English here.", "Rewrite in the passive.", "English is spoken here."),
                ("They built the house in 1990.", "Rewrite in the passive.", "The house was built in 1990."),
                ("Someone cleaned the room.", "Rewrite in the passive.", "The room was cleaned."),
                ("They send the emails every day.", "Rewrite in the passive.", "The emails are sent every day."),
            ],
            "mistake_type": "passive_form",
        },
    ],
    "b2": [
        {
            "topic_id": "second_conditional",
            "title": "Second Conditional",
            "summary": "Use the second conditional for unreal or unlikely present and future situations.",
            "structure": ["If + past simple, would + base verb"],
            "examples": ["If I had more time, I would travel.", "She would help if she knew.", "If we lived near the sea, we would swim every day."],
            "common_mistakes": ["Using would in the if-clause.", "Using present simple instead of past simple.", "Confusing first and second conditional meaning."],
            "mc_gap_pairs": [
                ("If I ___ rich, I would travel more.", "were", ["am", "would be", "was"]),
                ("She would call you if she ___ your number.", "had", ["has", "would have", "have"]),
                ("If we lived near the sea, we ___ every day.", "would swim", ["swam", "will swim", "would swam"]),
                ("He ___ happier if he worked less.", "would be", ["is", "will be", "would is"]),
                ("If they ___ more time, they would join us.", "had", ["have", "would have", "has"]),
                ("I would buy it if it ___ cheaper.", "were", ["is", "would be", "was"]),
                ("If you studied harder, you ___ better marks.", "would get", ["got", "will get", "would got"]),
                ("We would stay outside if it ___ warmer.", "were", ["is", "would be", "was"]),
            ],
            "transformations": [
                ("I do not have time, so I do not travel.", "Rewrite using the second conditional.", "If I had time, I would travel."),
                ("She does not know the answer, so she does not help.", "Rewrite using the second conditional.", "If she knew the answer, she would help."),
                ("We are not rich, so we do not buy a boat.", "Rewrite using the second conditional.", "If we were rich, we would buy a boat."),
                ("He does not live here, so he does not see us often.", "Rewrite using the second conditional.", "If he lived here, he would see us often."),
            ],
            "mistake_type": "second_conditional_form",
        },
        {
            "topic_id": "third_conditional",
            "title": "Third Conditional",
            "summary": "Use the third conditional for unreal past situations and regrets.",
            "structure": ["If + past perfect, would have + past participle"],
            "examples": ["If I had studied more, I would have passed.", "She would have called if she had known.", "If we had left earlier, we would have caught the train."],
            "common_mistakes": ["Using would have in the if-clause.", "Using past simple instead of past perfect.", "Confusing second and third conditionals."],
            "mc_gap_pairs": [
                ("If I had left earlier, I ___ the bus.", "would have caught", ["would catch", "caught", "had caught"]),
                ("She would have helped if she ___ there.", "had been", ["was", "would be", "has been"]),
                ("If we had known, we ___ you.", "would have told", ["would tell", "told", "had told"]),
                ("He ___ happier if he had taken the job.", "would have been", ["would be", "was", "had been"]),
                ("If they had studied, they ___ the test.", "would have passed", ["would pass", "passed", "had passed"]),
                ("I would have bought it if it ___ cheaper.", "had been", ["was", "would be", "has been"]),
                ("If you had called, I ___ home.", "would have stayed", ["would stay", "stayed", "had stayed"]),
                ("We would have arrived on time if the traffic ___ lighter.", "had been", ["was", "would be", "has been"]),
            ],
            "transformations": [
                ("I missed the bus, so I was late.", "Rewrite using the third conditional.", "If I had caught the bus, I would not have been late."),
                ("She did not study, so she failed.", "Rewrite using the third conditional.", "If she had studied, she would have passed."),
                ("We left late, so we missed the train.", "Rewrite using the third conditional.", "If we had left earlier, we would have caught the train."),
                ("He did not call me, so I did not know.", "Rewrite using the third conditional.", "If he had called me, I would have known."),
            ],
            "mistake_type": "third_conditional_form",
        },
        {
            "topic_id": "wish_if_only",
            "title": "Wish / If Only",
            "summary": "Use wish and if only to express regret about present or past situations.",
            "structure": ["wish + past simple", "wish + past perfect"],
            "examples": ["I wish I knew.", "If only it were warmer.", "She wishes she had studied more."],
            "common_mistakes": ["Using present simple after wish for present regret.", "Using would incorrectly for personal state.", "Confusing past regret with present regret."],
            "mc_gap_pairs": [
                ("I wish I ___ more time.", "had", ["have", "would have", "has"]),
                ("If only it ___ warmer today.", "were", ["is", "would be", "was"]),
                ("She wishes she ___ harder last year.", "had studied", ["studied", "would study", "has studied"]),
                ("We wish we ___ closer to the city.", "lived", ["live", "would live", "had lived"]),
                ("He wishes he ___ the truth.", "had told", ["told", "would tell", "has told"]),
                ("If only I ___ better at maths.", "were", ["am", "would be", "was"]),
                ("They wish they ___ earlier yesterday.", "had left", ["left", "would leave", "have left"]),
                ("I wish my phone ___ faster.", "worked", ["works", "would work", "had worked"]),
            ],
            "transformations": [
                ("I am not rich.", "Rewrite using wish.", "I wish I were rich."),
                ("She did not study enough.", "Rewrite using wishes.", "She wishes she had studied enough."),
                ("It is very cold today.", "Rewrite using if only.", "If only it were warmer today."),
                ("We arrived late yesterday.", "Rewrite using wish.", "We wish we had arrived earlier yesterday."),
            ],
            "mistake_type": "wish_form",
        },
    ],
    "c1": [
        {
            "topic_id": "inversion",
            "title": "Inversion",
            "summary": "Use inversion after negative or limiting adverbials for emphasis in formal English.",
            "structure": ["Never have I seen...", "Rarely does he..."],
            "examples": ["Never have I seen such a mess.", "Rarely does he complain.", "Only then did I understand."],
            "common_mistakes": ["Keeping normal word order after negative adverbials.", "Forgetting auxiliary do/did/has.", "Using inversion in informal contexts where it sounds unnatural."],
            "mc_gap_pairs": [
                ("Never ___ I seen such a view.", "have", ["had", "did", "am"]),
                ("Rarely ___ she complain.", "does", ["do", "is", "has"]),
                ("Only then ___ I understand the problem.", "did", ["do", "have", "was"]),
                ("Seldom ___ they arrive on time.", "do", ["did", "are", "have"]),
                ("Not only ___ he late, but he was also unprepared.", "was", ["did", "has", "is"]),
                ("Hardly ever ___ we see them now.", "do", ["did", "have", "are"]),
                ("Little ___ she know what would happen next.", "did", ["does", "had", "was"]),
                ("Under no circumstances ___ you open the door.", "should", ["do", "are", "have"]),
            ],
            "transformations": [
                ("I have never seen such a mess.", "Rewrite using inversion with never.", "Never have I seen such a mess."),
                ("She rarely complains.", "Rewrite using inversion with rarely.", "Rarely does she complain."),
                ("I only understood then.", "Rewrite using inversion with only then.", "Only then did I understand."),
                ("You should not open the door under any circumstances.", "Rewrite using inversion.", "Under no circumstances should you open the door."),
            ],
            "mistake_type": "inversion_pattern",
        },
        {
            "topic_id": "advanced_conditionals",
            "title": "Advanced Conditionals",
            "summary": "Use mixed and advanced conditionals to connect unreal past and present situations.",
            "structure": ["If + past perfect, would + base verb", "If + past simple, would have + past participle"],
            "examples": ["If I had studied medicine, I would be a doctor now.", "If he were more careful, he would not have made that mistake.", "Had I known, I would have acted differently."],
            "common_mistakes": ["Using standard conditionals where a mixed meaning is needed.", "Mixing time references incorrectly.", "Forgetting inversion in formal mixed conditionals."],
            "mc_gap_pairs": [
                ("If I had studied medicine, I ___ a doctor now.", "would be", ["would have been", "am", "was"]),
                ("If he were more careful, he ___ that mistake yesterday.", "would not have made", ["would not make", "did not make", "had not made"]),
                ("Had I known, I ___ differently.", "would have acted", ["would act", "acted", "had acted"]),
                ("If they had left earlier, they ___ here by now.", "would be", ["would have been", "are", "were"]),
                ("If she were more confident, she ___ the job last week.", "would have accepted", ["would accept", "accepted", "had accepted"]),
                ("Had we prepared better, we ___ calmer now.", "would feel", ["would have felt", "feel", "felt"]),
                ("If I had listened to you, I ___ in trouble now.", "would not be", ["would not have been", "am not", "was not"]),
                ("If he were less stubborn, he ___ earlier yesterday.", "would have apologised", ["would apologise", "apologised", "had apologised"]),
            ],
            "transformations": [
                ("I did not study medicine, so I am not a doctor now.", "Rewrite using a mixed conditional.", "If I had studied medicine, I would be a doctor now."),
                ("He is careless, so he made that mistake.", "Rewrite using a mixed conditional.", "If he were more careful, he would not have made that mistake."),
                ("We did not prepare well, so we feel nervous now.", "Rewrite using a mixed conditional.", "If we had prepared better, we would feel calmer now."),
                ("She is shy, so she did not accept the job.", "Rewrite using a mixed conditional.", "If she were more confident, she would have accepted the job."),
            ],
            "mistake_type": "mixed_conditional",
        },
    ],
}


TOPICS_BY_LEVEL["a1"].extend(
    [
        {
            "topic_id": "personal_pronouns",
            "title": "Personal Pronouns",
            "summary": "Use subject pronouns like I, you, he, she, it, we, and they as the subject of the sentence.",
            "structure": ["I / you / he / she / it / we / they + verb"],
            "examples": ["She is my friend.", "They live nearby.", "It is on the table."],
            "common_mistakes": ["Using object pronouns as the subject.", "Confusing he and she.", "Using they for a singular thing."],
            "mc_gap_pairs": [
                ("___ is my brother.", "He", ["Him", "His", "They"]),
                ("___ are from Italy.", "They", ["Them", "Their", "It"]),
                ("___ am very tired.", "I", ["Me", "My", "She"]),
                ("___ is a big dog.", "It", ["Its", "They", "Them"]),
                ("___ are late again.", "You", ["Your", "Yours", "He"]),
                ("___ live in Madrid.", "We", ["Us", "Our", "It"]),
                ("___ is my English teacher.", "She", ["Her", "Hers", "They"]),
                ("___ is on the chair.", "It", ["Its", "Them", "We"]),
            ],
            "transformations": [
                ("Anna is my friend.", "Replace the name with a pronoun.", "She is my friend."),
                ("Tom and I are ready.", "Replace the names with a pronoun.", "We are ready."),
                ("The book is new.", "Replace the noun with a pronoun.", "It is new."),
                ("My parents are busy.", "Replace the noun phrase with a pronoun.", "They are busy."),
            ],
            "mistake_type": "personal_pronoun_choice",
        },
        {
            "topic_id": "singular_and_plural",
            "title": "Singular and Plural",
            "summary": "Use singular nouns for one thing and plural nouns for two or more things.",
            "structure": ["one book / two books", "one child / two children"],
            "examples": ["I have one cat.", "She has two bags.", "The children are outside."],
            "common_mistakes": ["Forgetting -s in regular plurals.", "Using one with plural nouns.", "Missing irregular plural forms."],
            "mc_gap_pairs": [
                ("I have two ___.", "books", ["book", "bookes", "booking"]),
                ("There is one ___ on the desk.", "pen", ["pens", "pens", "penes"]),
                ("Three ___ are in the room.", "children", ["child", "childs", "childes"]),
                ("My friend has four ___.", "boxes", ["box", "boxs", "boxen"]),
                ("One ___ is open.", "window", ["windows", "windows", "windoes"]),
                ("Two ___ are sleeping.", "babies", ["baby", "babys", "babyes"]),
                ("Five ___ are playing outside.", "boys", ["boy", "boies", "boyes"]),
                ("There is one ___ in the garden.", "woman", ["women", "womans", "womanes"]),
            ],
            "transformations": [
                ("one apple", "Rewrite in the plural.", "two apples"),
                ("three child", "Rewrite correctly.", "three children"),
                ("one boxes", "Rewrite correctly.", "one box"),
                ("two woman", "Rewrite correctly.", "two women"),
            ],
            "mistake_type": "plural_form",
        },
        {
            "topic_id": "possessives",
            "title": "Possessives",
            "summary": "Use possessive adjectives like my, your, his, her, our, and their before nouns.",
            "structure": ["my book", "her bag", "their house"],
            "examples": ["This is my phone.", "Her car is blue.", "Their teacher is kind."],
            "common_mistakes": ["Using subject pronouns instead of possessives.", "Confusing its and it's.", "Using his for a female owner."],
            "mc_gap_pairs": [
                ("This is ___ bag.", "my", ["I", "me", "mine"]),
                ("He loves ___ dog.", "his", ["he", "him", "their"]),
                ("She is with ___ sister.", "her", ["she", "hers", "his"]),
                ("We like ___ school.", "our", ["we", "us", "ours"]),
                ("They are in ___ house.", "their", ["they", "them", "theirs"]),
                ("I know ___ name.", "your", ["you", "yours", "we"]),
                ("The cat is in ___ bed.", "its", ["it's", "it", "their"]),
                ("Anna and I are doing ___ homework.", "our", ["my", "we", "ours"]),
            ],
            "transformations": [
                ("This bag belongs to me.", "Rewrite with a possessive adjective.", "This is my bag."),
                ("That car belongs to her.", "Rewrite with a possessive adjective.", "That is her car."),
                ("This room belongs to us.", "Rewrite with a possessive adjective.", "This is our room."),
                ("The toys belong to them.", "Rewrite with a possessive adjective.", "Those are their toys."),
            ],
            "mistake_type": "possessive_adjective",
        },
        {
            "topic_id": "basic_prepositions_of_place",
            "title": "Basic Prepositions of Place",
            "summary": "Use in, on, under, next to, between, and behind to describe where things are.",
            "structure": ["in the box", "on the table", "under the chair"],
            "examples": ["The keys are on the table.", "The cat is under the bed.", "The bank is next to the shop."],
            "common_mistakes": ["Confusing in and on.", "Using under instead of below or next to.", "Forgetting the noun after the preposition."],
            "mc_gap_pairs": [
                ("The book is ___ the table.", "on", ["in", "under", "between"]),
                ("The shoes are ___ the bed.", "under", ["on", "in", "between"]),
                ("The milk is ___ the fridge.", "in", ["on", "under", "between"]),
                ("The bank is ___ the cafe.", "next to", ["under", "in", "on"]),
                ("The ball is ___ the chair and the table.", "between", ["behind", "on", "in"]),
                ("The car is ___ the house.", "behind", ["on", "in", "between"]),
                ("The picture is ___ the wall.", "on", ["in", "under", "between"]),
                ("My phone is ___ my bag.", "in", ["on", "between", "behind"]),
            ],
            "transformations": [
                ("The cat is under the chair.", "Rewrite as a question.", "Is the cat under the chair?"),
                ("The keys are on the desk.", "Rewrite as a negative sentence.", "The keys are not on the desk."),
                ("The shop is next to the bank.", "Rewrite as a question.", "Is the shop next to the bank?"),
                ("The ball is in the box.", "Rewrite as a negative sentence.", "The ball is not in the box."),
            ],
            "mistake_type": "preposition_of_place",
        },
    ]
)

TOPICS_BY_LEVEL["a2"].extend(
    [
        {
            "topic_id": "countable_uncountable",
            "title": "Countable and Uncountable Nouns",
            "summary": "Countable nouns can be counted, while uncountable nouns usually use singular forms and quantity words.",
            "structure": ["a book / two books", "some water / much water"],
            "examples": ["I need a chair.", "There is some rice on the plate.", "She bought three apples."],
            "common_mistakes": ["Using a/an with uncountable nouns.", "Making uncountable nouns plural.", "Using many with uncountable nouns."],
            "mc_gap_pairs": [
                ("I need some ___.", "water", ["waters", "a water", "many water"]),
                ("There are three ___ on the table.", "apples", ["apple", "water", "rice"]),
                ("She bought a ___ of bread.", "loaf", ["bread", "breads", "many bread"]),
                ("We do not have much ___.", "time", ["times", "a time", "many times"]),
                ("How many ___ do you have?", "books", ["book", "milk", "bread"]),
                ("There is some ___ in the fridge.", "milk", ["milks", "a milk", "many milk"]),
                ("I ate two ___.", "sandwiches", ["sandwich", "rice", "bread"]),
                ("He gave me useful ___.", "advice", ["advices", "an advice", "many advice"]),
            ],
            "transformations": [
                ("many water", "Rewrite correctly.", "much water"),
                ("an advice", "Rewrite correctly.", "some advice"),
                ("two bread", "Rewrite correctly.", "two loaves of bread"),
                ("three apple", "Rewrite correctly.", "three apples"),
            ],
            "mistake_type": "countable_uncountable",
        },
        {
            "topic_id": "some_any_much_many",
            "title": "Some / Any / Much / Many",
            "summary": "Use some in positive statements, any in questions and negatives, many with countable nouns, and much with uncountable nouns.",
            "structure": ["some apples", "any milk", "many books", "much time"],
            "examples": ["I have some friends.", "Do you have any money?", "There are many cars outside."],
            "common_mistakes": ["Using some in negatives.", "Using much with countable nouns.", "Using many with uncountable nouns."],
            "mc_gap_pairs": [
                ("I have ___ friends at school.", "some", ["any", "much", "many"]),
                ("Do you have ___ sugar?", "any", ["some", "many", "much"]),
                ("There are ___ students here.", "many", ["much", "some", "any"]),
                ("We do not have ___ time.", "much", ["many", "some", "a few"]),
                ("Can I have ___ water, please?", "some", ["any", "many", "much"]),
                ("Are there ___ books on the shelf?", "any", ["some", "much", "many"]),
                ("How ___ money do you need?", "much", ["many", "some", "any"]),
                ("How ___ apples are there?", "many", ["much", "some", "any"]),
            ],
            "transformations": [
                ("I do not have some money.", "Rewrite correctly.", "I do not have any money."),
                ("How much apples do you want?", "Rewrite correctly.", "How many apples do you want?"),
                ("There are much cars outside.", "Rewrite correctly.", "There are many cars outside."),
                ("Can I have any water?", "Rewrite as a polite offer request with some.", "Can I have some water?"),
            ],
            "mistake_type": "quantity_word_choice",
        },
        {
            "topic_id": "adverbs_of_frequency",
            "title": "Adverbs of Frequency",
            "summary": "Use adverbs like always, usually, often, sometimes, and never to show how often something happens.",
            "structure": ["subject + adverb + main verb", "subject + be + adverb"],
            "examples": ["I usually get up at seven.", "She is always late.", "They never eat meat."],
            "common_mistakes": ["Putting the adverb in the wrong place.", "Using never with another negative.", "Misplacing adverbs with the verb be."],
            "mc_gap_pairs": [
                ("I ___ drink coffee in the morning.", "usually", ["drink", "am", "never not"]),
                ("She is ___ happy after class.", "always", ["goes", "eat", "usually goes"]),
                ("They ___ go to the cinema on Fridays.", "often", ["are", "is", "never not"]),
                ("He is ___ late for work.", "sometimes", ["go", "never not", "drives"]),
                ("We ___ eat fast food.", "never", ["are", "is", "always are"]),
                ("My dad ___ watches TV after dinner.", "often", ["is", "are", "never not"]),
                ("I am ___ tired after the gym.", "usually", ["go", "plays", "drink"]),
                ("She ___ walks to school.", "always", ["is", "are", "never not"]),
            ],
            "transformations": [
                ("I go to bed late. usually", "Rewrite correctly.", "I usually go to bed late."),
                ("She late is always.", "Rewrite correctly.", "She is always late."),
                ("They do not never eat fish.", "Rewrite correctly.", "They never eat fish."),
                ("He is sometimes tired after work.", "Rewrite with the same meaning.", "He is sometimes tired after work."),
            ],
            "mistake_type": "adverb_position",
        },
        {
            "topic_id": "basic_modals",
            "title": "Basic Modals",
            "summary": "Use can, can't, must, and mustn't for ability, permission, and basic rules.",
            "structure": ["can + verb", "must + verb", "mustn't + verb"],
            "examples": ["She can swim.", "You must stop here.", "We mustn't be late."],
            "common_mistakes": ["Adding to after a modal.", "Using -s after can or must.", "Confusing can't and mustn't."],
            "mc_gap_pairs": [
                ("She ___ swim very well.", "can", ["to can", "cans", "must to"]),
                ("You ___ wear a seat belt.", "must", ["must to", "musts", "can to"]),
                ("We ___ smoke here.", "mustn't", ["don't must", "can't to", "must not to"]),
                ("I ___ speak Spanish a little.", "can", ["am can", "cans", "to can"]),
                ("Students ___ run in the corridor.", "mustn't", ["must not to", "don't can", "musts"]),
                ("You ___ finish your homework today.", "must", ["must to", "musts", "to must"]),
                ("He ___ play the piano.", "can", ["plays", "can to", "cans"]),
                ("You ___ touch that button.", "mustn't", ["must not to", "can't to", "musts"]),
            ],
            "transformations": [
                ("She is able to swim.", "Rewrite with can.", "She can swim."),
                ("It is necessary to stop here.", "Rewrite with must.", "You must stop here."),
                ("It is not allowed to smoke here.", "Rewrite with mustn't.", "You mustn't smoke here."),
                ("He can drive.", "Rewrite as a question.", "Can he drive?"),
            ],
            "mistake_type": "basic_modal_form",
        },
    ]
)

TOPICS_BY_LEVEL["b1"].extend(
    [
        {
            "topic_id": "present_perfect_vs_past_simple",
            "title": "Present Perfect vs Past Simple",
            "summary": "Use Present Perfect for life experience or unfinished time, and Past Simple for finished past time.",
            "structure": ["have/has + V3", "verb-ed / irregular past form"],
            "examples": ["I have been to Rome.", "I went to Rome last year.", "She has just arrived."],
            "common_mistakes": ["Using yesterday with Present Perfect.", "Using Past Simple for life experience without a time.", "Mixing for and ago."],
            "mc_gap_pairs": [
                ("I ___ to Paris last year.", "went", ["have gone", "have been", "go"]),
                ("She ___ never ___ sushi.", "has eaten", ["ate", "has eat", "have eaten"]),
                ("We ___ our homework yesterday.", "finished", ["have finished", "finish", "have finish"]),
                ("He ___ just ___.", "has arrived", ["arrived", "have arrived", "has arrive"]),
                ("They ___ this film already.", "have seen", ["saw", "have saw", "seen"]),
                ("I ___ him two days ago.", "met", ["have met", "meet", "have meet"]),
                ("My sister ___ in London in 2022.", "lived", ["has lived", "live", "has live"]),
                ("___ you ever ___ to Berlin?", "Have been", ["Did go", "Have went", "Were gone"]),
            ],
            "transformations": [
                ("I have visited London in 2021.", "Rewrite correctly.", "I visited London in 2021."),
                ("She went to Japan before.", "Rewrite for life experience.", "She has been to Japan before."),
                ("We have finished it yesterday.", "Rewrite correctly.", "We finished it yesterday."),
                ("Did you ever eat sushi?", "Rewrite with Present Perfect.", "Have you ever eaten sushi?"),
            ],
            "mistake_type": "pp_vs_past_simple",
        },
        {
            "topic_id": "modals_advice_obligation",
            "title": "Modals of Advice and Obligation",
            "summary": "Use should for advice and must / have to for obligation.",
            "structure": ["should + verb", "must + verb", "have to + verb"],
            "examples": ["You should rest.", "I must leave now.", "She has to work tomorrow."],
            "common_mistakes": ["Using to after should or must.", "Confusing must and have to.", "Adding -s after a modal."],
            "mc_gap_pairs": [
                ("You ___ see a doctor.", "should", ["should to", "must to", "shoulds"]),
                ("I ___ finish this report today.", "have to", ["must to", "having to", "has to"]),
                ("Students ___ wear uniforms at this school.", "have to", ["should to", "musts", "must to"]),
                ("You ___ eat so much sugar.", "shouldn't", ["don't should", "should not to", "mustn't to"]),
                ("He ___ be at the office by 9.", "has to", ["have to", "must to", "should to"]),
                ("We ___ tell her the truth.", "should", ["should to", "must to", "shoulds"]),
                ("You ___ park here.", "mustn't", ["mustn't to", "don't must", "shouldn't to"]),
                ("She ___ take an umbrella; it looks rainy.", "should", ["has to", "should to", "must to"]),
            ],
            "transformations": [
                ("It is a good idea to rest more.", "Rewrite with should.", "You should rest more."),
                ("It is necessary for her to wear a uniform.", "Rewrite with have to.", "She has to wear a uniform."),
                ("It is not allowed to park here.", "Rewrite with mustn't.", "You mustn't park here."),
                ("You should call him.", "Rewrite as a negative sentence.", "You shouldn't call him."),
            ],
            "mistake_type": "advice_obligation_modal",
        },
        {
            "topic_id": "relative_clauses",
            "title": "Relative Clauses",
            "summary": "Use who, which, that, and where to add information about a person, thing, or place.",
            "structure": ["the man who...", "the book that...", "the place where..."],
            "examples": ["The woman who lives next door is a doctor.", "This is the book that I bought.", "That is the cafe where we met."],
            "common_mistakes": ["Using which for people.", "Forgetting the relative pronoun.", "Using where for things."],
            "mc_gap_pairs": [
                ("The girl ___ sits there is my cousin.", "who", ["which", "where", "what"]),
                ("This is the phone ___ I bought yesterday.", "that", ["who", "where", "whose"]),
                ("The city ___ I was born is small.", "where", ["who", "that", "which"]),
                ("The teacher ___ helped me was kind.", "who", ["which", "where", "what"]),
                ("I like books ___ make me think.", "that", ["who", "where", "whose"]),
                ("The restaurant ___ we had dinner was crowded.", "where", ["that", "who", "which"]),
                ("The friend ___ called me is in Spain.", "who", ["which", "where", "that place"]),
                ("The film ___ we watched was funny.", "that", ["who", "where", "whose"]),
            ],
            "transformations": [
                ("The woman lives next door. She is a doctor.", "Join the sentences with who.", "The woman who lives next door is a doctor."),
                ("This is the cafe. We met there.", "Join the sentences with where.", "This is the cafe where we met."),
                ("I have a book. It explains grammar.", "Join the sentences with that.", "I have a book that explains grammar."),
                ("The man is my uncle. He is wearing a hat.", "Join the sentences with who.", "The man who is wearing a hat is my uncle."),
            ],
            "mistake_type": "relative_clause_choice",
        },
        {
            "topic_id": "basic_reported_speech",
            "title": "Basic Reported Speech",
            "summary": "Use reported speech to tell someone what another person said, often with backshift in tense.",
            "structure": ["say that...", "tell someone that...", "present -> past"],
            "examples": ["She said that she was tired.", "He told me that he had a car.", "They said that they were busy."],
            "common_mistakes": ["Keeping the original tense when backshift is needed.", "Using tell without an object.", "Forgetting that word order changes in questions."],
            "mc_gap_pairs": [
                ("She said that she ___ tired.", "was", ["is", "be", "were being"]),
                ("He told me that he ___ a car.", "had", ["has", "have", "having"]),
                ("They said that they ___ busy.", "were", ["are", "be", "was"]),
                ("Anna said that she ___ the answer.", "knew", ["knows", "know", "has known"]),
                ("Tom told us that he ___ home early.", "was going", ["is going", "goes", "has gone"]),
                ("She said that she ___ coffee every morning.", "drank", ["drinks", "drink", "is drinking"]),
                ("He told me that he ___ the film before.", "had seen", ["has seen", "saw", "see"]),
                ("They said that they ___ to help.", "wanted", ["want", "have wanted", "are wanting"]),
            ],
            "transformations": [
                ("She said, 'I am tired.'", "Rewrite in reported speech.", "She said that she was tired."),
                ("He told me, 'I have a car.'", "Rewrite in reported speech.", "He told me that he had a car."),
                ("They said, 'We are busy.'", "Rewrite in reported speech.", "They said that they were busy."),
                ("Anna said, 'I know the answer.'", "Rewrite in reported speech.", "Anna said that she knew the answer."),
            ],
            "mistake_type": "reported_speech_backshift",
        },
    ]
)

TOPICS_BY_LEVEL["b2"].extend(
    [
        {
            "topic_id": "advanced_passive",
            "title": "Advanced Passive",
            "summary": "Use advanced passive structures in different tenses and with reporting verbs.",
            "structure": ["is being done", "has been done", "is said to..."],
            "examples": ["The bridge is being repaired.", "The work has been finished.", "He is said to be very rich."],
            "common_mistakes": ["Using the wrong form of be.", "Forgetting been in perfect passive.", "Keeping active word order."],
            "mc_gap_pairs": [
                ("The road ___ right now.", "is being repaired", ["is repaired", "repairs", "has repaired"]),
                ("The report ___ already.", "has been finished", ["has finished", "was finishing", "has being finished"]),
                ("English ___ in many countries.", "is spoken", ["speaks", "is speaking", "has spoken"]),
                ("The suspect ___ to the station yesterday.", "was taken", ["took", "has taken", "was taking"]),
                ("The dinner ___ by 8 p.m.", "will be served", ["will serve", "serves", "will served"]),
                ("She ___ to be an excellent surgeon.", "is said", ["says", "has said", "was saying"]),
                ("The problem ___ yet.", "has not been solved", ["has not solved", "was not solving", "did not solve"]),
                ("New houses ___ here next year.", "will be built", ["will build", "build", "are built"]),
            ],
            "transformations": [
                ("They are repairing the road.", "Rewrite in the passive.", "The road is being repaired."),
                ("Someone has finished the report.", "Rewrite in the passive.", "The report has been finished."),
                ("People say she is very talented.", "Rewrite with a reporting passive.", "She is said to be very talented."),
                ("They will build new houses here.", "Rewrite in the passive.", "New houses will be built here."),
            ],
            "mistake_type": "advanced_passive_form",
        },
        {
            "topic_id": "advanced_reported_speech",
            "title": "Advanced Reported Speech",
            "summary": "Use advanced reported speech for commands, requests, questions, and reporting verbs.",
            "structure": ["told me to...", "asked if...", "explained that..."],
            "examples": ["She told me to wait.", "He asked if I was ready.", "They warned us not to be late."],
            "common_mistakes": ["Using normal question order after asked.", "Forgetting to-infinitive after tell or ask for commands.", "Using say with an object in the wrong way."],
            "mc_gap_pairs": [
                ("She told me ___ there.", "to wait", ["wait", "waiting", "that wait"]),
                ("He asked if I ___ ready.", "was", ["am", "be", "have been"]),
                ("They warned us ___ late.", "not to be", ["to not be", "not be", "don't be"]),
                ("Anna asked me where I ___ .", "lived", ["do I live", "live", "am living"]),
                ("He advised us ___ early.", "to leave", ["leave", "leaving", "that leave"]),
                ("She asked whether I ___ help.", "needed", ["need", "do I need", "have need"]),
                ("Tom told me ___ the door.", "to close", ["close", "closing", "that close"]),
                ("They asked what time the train ___.", "left", ["does it leave", "leave", "is leaving"]),
            ],
            "transformations": [
                ("She said to me, 'Wait here.'", "Rewrite in reported speech.", "She told me to wait there."),
                ("He asked, 'Are you ready?'", "Rewrite in reported speech.", "He asked if I was ready."),
                ("They said, 'Don't be late.'", "Rewrite in reported speech.", "They warned us not to be late."),
                ("Anna asked, 'Where do you live?'", "Rewrite in reported speech.", "Anna asked where I lived."),
            ],
            "mistake_type": "advanced_reported_speech",
        },
        {
            "topic_id": "modal_deduction",
            "title": "Modal Deduction",
            "summary": "Use must, might, may, and can't to guess or deduce how likely something is.",
            "structure": ["must be", "might be", "can't be", "must have been"],
            "examples": ["She must be tired.", "It might rain later.", "That can't be right."],
            "common_mistakes": ["Using to after the modal.", "Confusing mustn't with can't for deduction.", "Using wrong perfect forms for past deduction."],
            "mc_gap_pairs": [
                ("She worked all night. She ___ tired.", "must be", ["must to be", "can't to be", "might being"]),
                ("I am not sure. It ___ rain later.", "might", ["must to", "can't to", "mights"]),
                ("That answer is impossible. It ___ right.", "can't be", ["mustn't be", "can't to be", "must be"]),
                ("The lights are off. They ___ at home.", "can't be", ["mustn't be", "might to be", "must to be"]),
                ("He has the keys. He ___ the car.", "must have taken", ["must took", "must has taken", "can't have taking"]),
                ("I do not know where she is. She ___ at work.", "may be", ["must to be", "may to be", "can't being"]),
                ("The ground is wet. It ___ last night.", "must have rained", ["must rained", "must have rain", "can't have raining"]),
                ("He looks familiar. I ___ him before.", "must have met", ["must met", "must have meet", "might to met"]),
            ],
            "transformations": [
                ("I am sure she is tired.", "Rewrite with a modal of deduction.", "She must be tired."),
                ("It is possible that he is at home.", "Rewrite with a modal of deduction.", "He might be at home."),
                ("I am sure that is not true.", "Rewrite with a modal of deduction.", "That can't be true."),
                ("I am sure it rained last night.", "Rewrite with a modal of past deduction.", "It must have rained last night."),
            ],
            "mistake_type": "modal_deduction_form",
        },
        {
            "topic_id": "discourse_markers",
            "title": "Discourse Markers",
            "summary": "Use discourse markers like however, therefore, although, and in addition to connect ideas clearly.",
            "structure": ["However, ...", "Therefore, ...", "In addition, ...", "Although ..."],
            "examples": ["It was late. However, we kept working.", "She was tired; therefore, she went home."],
            "common_mistakes": ["Choosing a marker with the wrong meaning.", "Using however like and.", "Mixing although and therefore."],
            "mc_gap_pairs": [
                ("It was raining. ___, we went for a walk.", "However", ["Therefore", "In addition", "For example"]),
                ("She studied hard. ___, she passed the exam.", "Therefore", ["However", "Although", "Besides of"]),
                ("___ he was tired, he finished the work.", "Although", ["Therefore", "However", "In addition"]),
                ("The hotel was cheap. ___, it was clean.", "In addition", ["Therefore", "However", "Although"]),
                ("I love travelling. ___, I do not have much time.", "However", ["Therefore", "For this reason", "In addition"]),
                ("He missed the bus. ___, he was late.", "Therefore", ["However", "Although", "In addition"]),
                ("___ it was expensive, we bought it.", "Although", ["Therefore", "However", "In addition"]),
                ("The course is useful. ___, it is well organised.", "In addition", ["Therefore", "Although", "However"]),
            ],
            "transformations": [
                ("It was raining, but we went out.", "Rewrite using however.", "It was raining. However, we went out."),
                ("She studied hard, so she passed.", "Rewrite using therefore.", "She studied hard. Therefore, she passed."),
                ("It was expensive, but we bought it.", "Rewrite using although.", "Although it was expensive, we bought it."),
                ("The app is useful and easy to use.", "Rewrite using in addition.", "The app is useful. In addition, it is easy to use."),
            ],
            "mistake_type": "discourse_marker_choice",
        },
        {
            "topic_id": "defining_non_defining_relative_clauses",
            "title": "Defining and Non-defining Relative Clauses",
            "summary": "Use defining clauses for essential information and non-defining clauses for extra information, usually with commas.",
            "structure": ["The people who live here...", "My brother, who lives in Rome, ..."],
            "examples": ["The students who work hard succeed.", "My aunt, who is a doctor, lives in Leeds."],
            "common_mistakes": ["Missing commas in non-defining clauses.", "Using that in non-defining clauses.", "Choosing the wrong relative pronoun."],
            "mc_gap_pairs": [
                ("My sister, ___ lives in Rome, is visiting us.", "who", ["that", "where", "whose place"]),
                ("The book ___ you gave me is excellent.", "that", ["who", "where", "which one there"]),
                ("Paris, ___ is very beautiful, is expensive.", "which", ["that", "where", "whose"]),
                ("The students ___ arrive late must wait outside.", "who", ["which", "where", "whose"]),
                ("My laptop, ___ I bought last year, still works well.", "which", ["that", "where", "whose"]),
                ("The cafe ___ serves vegan food is near here.", "that", ["which one", "where there", "who"]),
                ("My friend, ___ father is a pilot, travels a lot.", "whose", ["who", "that", "where"]),
                ("The office ___ we work is on the fifth floor.", "where", ["that person", "who", "whose"]),
            ],
            "transformations": [
                ("My sister lives in Rome. She is visiting us.", "Join with a non-defining relative clause.", "My sister, who lives in Rome, is visiting us."),
                ("The book is excellent. You gave it to me.", "Join with a defining relative clause.", "The book that you gave me is excellent."),
                ("My friend has a father. His father is a pilot.", "Rewrite with whose.", "My friend, whose father is a pilot, travels a lot."),
                ("The cafe is near here. It serves vegan food.", "Join with a defining relative clause.", "The cafe that serves vegan food is near here."),
            ],
            "mistake_type": "relative_clause_type",
        },
    ]
)

TOPICS_BY_LEVEL["c1"].extend(
    [
        {
            "topic_id": "cleft_sentences",
            "title": "Cleft Sentences",
            "summary": "Use cleft sentences to emphasize one part of a sentence.",
            "structure": ["It was X that...", "What I need is..."],
            "examples": ["It was John who called.", "What I need is a break.", "The reason why I left was the noise."],
            "common_mistakes": ["Keeping normal word order after it was.", "Using the wrong cleft pattern.", "Overusing clefts in very simple contexts."],
            "mc_gap_pairs": [
                ("It was Anna ___ solved the problem.", "who", ["which", "where", "what"]),
                ("What I need ___ a holiday.", "is", ["are", "be", "were"]),
                ("It was yesterday ___ we met.", "that", ["who", "where", "what"]),
                ("The reason why I left ___ the noise.", "was", ["is", "were", "be"]),
                ("What surprised me most ___ his calm reaction.", "was", ["were", "is being", "be"]),
                ("It was the manager ___ approved the plan.", "who", ["which", "where", "what"]),
                ("What she wants ___ more independence.", "is", ["are", "be", "were"]),
                ("It was in Paris ___ they first met.", "that", ["who", "which", "what"]),
            ],
            "transformations": [
                ("Anna solved the problem.", "Rewrite with a cleft sentence.", "It was Anna who solved the problem."),
                ("I need a holiday.", "Rewrite with what-clause emphasis.", "What I need is a holiday."),
                ("We met yesterday.", "Rewrite with a cleft sentence.", "It was yesterday that we met."),
                ("The noise made me leave.", "Rewrite with reason emphasis.", "The reason why I left was the noise."),
            ],
            "mistake_type": "cleft_sentence_form",
        },
        {
            "topic_id": "participle_clauses",
            "title": "Participle Clauses",
            "summary": "Use participle clauses to make sentences shorter and more formal.",
            "structure": ["Walking down the street, ...", "Built in 1920, ...", "Having finished, ..."],
            "examples": ["Walking home, I saw him.", "Built in 1920, the house looks elegant.", "Having finished the task, she relaxed."],
            "common_mistakes": ["Using the wrong subject in the participle clause.", "Choosing present instead of past participle.", "Creating dangling modifiers."],
            "mc_gap_pairs": [
                ("___ down the street, I saw an old friend.", "Walking", ["Walked", "Walk", "Having walk"]),
                ("___ in 1920, the house still looks elegant.", "Built", ["Building", "Build", "Having build"]),
                ("___ the task, she went home.", "Having finished", ["Finishing", "Finished", "Having finish"]),
                ("___ by the noise, he looked outside.", "Disturbed", ["Disturbing", "Disturb", "Having disturb"]),
                ("___ at the map, we found the station.", "Looking", ["Looked", "Look", "Having look"]),
                ("___ in several languages, the book became famous.", "Written", ["Writing", "Write", "Having write"]),
                ("___ her answer, she felt relieved.", "Having submitted", ["Submitting", "Submitted", "Having submit"]),
                ("___ by sunlight, the room felt warm.", "Lit", ["Lighting", "Light", "Having light"]),
            ],
            "transformations": [
                ("When I was walking down the street, I saw an old friend.", "Rewrite with a participle clause.", "Walking down the street, I saw an old friend."),
                ("Because it was built in 1920, the house looks elegant.", "Rewrite with a participle clause.", "Built in 1920, the house looks elegant."),
                ("After she had finished the task, she went home.", "Rewrite with a participle clause.", "Having finished the task, she went home."),
                ("Because he was disturbed by the noise, he looked outside.", "Rewrite with a participle clause.", "Disturbed by the noise, he looked outside."),
            ],
            "mistake_type": "participle_clause_form",
        },
        {
            "topic_id": "ellipsis_and_substitution",
            "title": "Ellipsis and Substitution",
            "summary": "Use ellipsis and substitution to avoid repetition in advanced English.",
            "structure": ["I can do it, and so can she.", "I prefer the blue one."],
            "examples": ["I wanted the red one, not the blue one.", "He said he would help, and he did.", "She can swim, and so can I."],
            "common_mistakes": ["Repeating full phrases unnecessarily.", "Using one with uncountable nouns.", "Breaking agreement in substitution patterns."],
            "mc_gap_pairs": [
                ("I want the blue ___, not the red one.", "one", ["ones", "it", "that one piece"]),
                ("She said she would call, and she ___.", "did", ["was", "made", "done"]),
                ("I can swim, and so ___ my sister.", "can", ["does", "is", "did"]),
                ("These shoes are nicer than the old ___.", "ones", ["one", "it", "that"]),
                ("He promised to help, and he actually ___.", "did", ["was", "made", "done"]),
                ("She likes tea, and so ___ I.", "do", ["am", "did", "can"]),
                ("I need a pen. Do you have ___?", "one", ["it", "ones", "some one things"]),
                ("They said they would come, but they did not ___.", "do so", ["did", "come so", "be so"]),
            ],
            "transformations": [
                ("I want the blue shirt, not the red shirt.", "Rewrite using substitution.", "I want the blue one, not the red one."),
                ("She said she would help, and she helped.", "Rewrite using substitution.", "She said she would help, and she did."),
                ("I can swim and my sister can swim too.", "Rewrite with so.", "I can swim, and so can my sister."),
                ("They said they would come, but they did not come.", "Rewrite using do so.", "They said they would come, but they did not do so."),
            ],
            "mistake_type": "ellipsis_substitution",
        },
        {
            "topic_id": "advanced_modality",
            "title": "Advanced Modality",
            "summary": "Use advanced modals to express nuance, speculation, criticism, and degrees of certainty.",
            "structure": ["might have done", "should have done", "needn't have done"],
            "examples": ["You should have told me.", "They might have missed the train.", "You needn't have bought any food."],
            "common_mistakes": ["Using base verb instead of have + V3.", "Confusing didn't need to with needn't have.", "Using to after a modal."],
            "mc_gap_pairs": [
                ("You ___ me earlier.", "should have called", ["should called", "should have call", "must to call"]),
                ("They ___ the train; traffic was awful.", "might have missed", ["might missed", "might have miss", "must to miss"]),
                ("You ___ any food; we already had plenty.", "needn't have bought", ["didn't need bought", "needn't bought", "needn't have buy"]),
                ("She ___ at home; the lights are on.", "must be", ["must to be", "must have be", "must being"]),
                ("He ___ so much money on that.", "shouldn't have spent", ["shouldn't spent", "shouldn't have spend", "mustn't to spend"]),
                ("I ___ the wrong date in my diary.", "may have written", ["may wrote", "may have write", "may to write"]),
                ("We ___ so early; the meeting was delayed.", "needn't have arrived", ["didn't need arrived", "needn't arrived", "needn't have arrive"]),
                ("They ___ by now; the flight landed an hour ago.", "should be here", ["should have here", "must to be here", "should been here"]),
            ],
            "transformations": [
                ("It was a mistake not to call me earlier.", "Rewrite with should have.", "You should have called me earlier."),
                ("Perhaps they missed the train.", "Rewrite with might have.", "They might have missed the train."),
                ("It was unnecessary for you to buy food.", "Rewrite with needn't have.", "You needn't have bought any food."),
                ("I am almost certain she is at home.", "Rewrite with must be.", "She must be at home."),
            ],
            "mistake_type": "advanced_modality_form",
        },
        {
            "topic_id": "hedging",
            "title": "Hedging",
            "summary": "Use hedging language to sound cautious, polite, or less absolute.",
            "structure": ["It seems that...", "It may be the case that...", "tend to", "appear to"],
            "examples": ["It seems that the plan is working.", "This may not be entirely accurate.", "They tend to arrive late."],
            "common_mistakes": ["Sounding too direct in formal writing.", "Using absolute statements where hedging is better.", "Combining too many hedges awkwardly."],
            "mc_gap_pairs": [
                ("It ___ that the plan is working.", "seems", ["must", "absolutely", "proves"]),
                ("This ___ not be entirely accurate.", "may", ["is", "definitely", "must to"]),
                ("Students ___ struggle with this topic at first.", "tend to", ["must", "are always", "prove to"]),
                ("The results ___ suggest a slight improvement.", "appear to", ["must", "are surely", "do to"]),
                ("It is ___ possible that we need more time.", "perhaps", ["definitely", "absolutely", "totally"]),
                ("The change is ___ to affect small businesses more.", "likely", ["certainly always", "must", "surely to"]),
                ("This could ___ interpreted in two ways.", "be", ["being", "been", "to be"]),
                ("It would ___ be fair to say that progress is slow.", "probably", ["definitely", "absolutely", "surely always"]),
            ],
            "transformations": [
                ("The plan is working.", "Rewrite with hedging.", "It seems that the plan is working."),
                ("This is wrong.", "Rewrite with hedging.", "This may not be entirely accurate."),
                ("Students struggle with this topic.", "Rewrite with hedging.", "Students tend to struggle with this topic."),
                ("The results show improvement.", "Rewrite with hedging.", "The results appear to suggest improvement."),
            ],
            "mistake_type": "hedging_language",
        },
        {
            "topic_id": "formal_linking_devices",
            "title": "Formal Linking Devices",
            "summary": "Use formal linking devices to organize arguments in essays and professional writing.",
            "structure": ["Furthermore, ...", "Nevertheless, ...", "Consequently, ...", "In contrast, ..."],
            "examples": ["Furthermore, the policy is expensive.", "Nevertheless, we continued.", "Consequently, sales increased."],
            "common_mistakes": ["Using informal connectors in formal writing.", "Choosing a linker with the wrong meaning.", "Overusing one linker repeatedly."],
            "mc_gap_pairs": [
                ("The proposal is expensive. ___, it may still be worth adopting.", "Nevertheless", ["Consequently", "For example", "And"]),
                ("The team lacked resources. ___, they completed the project.", "Nevertheless", ["Consequently", "Furthermore", "So"]),
                ("Costs rose sharply. ___, several services were cut.", "Consequently", ["Nevertheless", "Furthermore", "And then"]),
                ("The method is fast. ___, it is also reliable.", "Furthermore", ["Nevertheless", "Consequently", "But"]),
                ("Online sales increased. ___, shop sales declined.", "In contrast", ["Consequently", "Furthermore", "So"]),
                ("The measure is unpopular. ___, it may be necessary.", "Nevertheless", ["Furthermore", "Consequently", "And"]),
                ("The company expanded rapidly. ___, it hired more staff.", "Consequently", ["Nevertheless", "In contrast", "But"]),
                ("The northern region grew, __ the southern region declined.", "whereas", ["therefore", "furthermore", "nevertheless"]),
            ],
            "transformations": [
                ("The method is fast. It is also reliable.", "Join the ideas more formally.", "Furthermore, the method is reliable."),
                ("Costs rose sharply, so services were cut.", "Rewrite with a more formal linker.", "Costs rose sharply. Consequently, several services were cut."),
                ("The policy is unpopular, but it may be necessary.", "Rewrite with a more formal linker.", "The policy is unpopular. Nevertheless, it may be necessary."),
                ("Online sales increased, but shop sales declined.", "Rewrite with a contrast linker.", "Online sales increased. In contrast, shop sales declined."),
            ],
            "mistake_type": "formal_linker_choice",
        },
    ]
)


def write_json(path: Path, payload: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


def build_content() -> None:
    for level, topics in TOPICS_BY_LEVEL.items():
        topic_rows = []
        for index, topic in enumerate(topics, start=1):
            topic_rows.append(
                {
                    "topic_id": topic["topic_id"],
                    "level": level.upper(),
                    "title": topic["title"],
                    "order": index,
                    "is_active": True,
                }
            )

            theory = {
                "topic_id": topic["topic_id"],
                "title": topic["title"],
                "summary": topic["summary"],
                "structure": topic["structure"],
                "examples": topic["examples"][:4],
                "common_mistakes": topic["common_mistakes"][:3],
            }
            write_json(ROOT / "theory" / f"{topic['topic_id']}.json", theory)

            exercises = []
            for num, (prompt, correct, distractors) in enumerate(topic["mc_gap_pairs"], start=1):
                exercises.append(
                    {
                        "exercise_id": f"{topic['topic_id']}_mc_{num:03d}",
                        "topic_id": topic["topic_id"],
                        "level": level.upper(),
                        "type": "multiple_choice",
                        "prompt": prompt,
                        "options": shuffled_options(
                            topic["topic_id"],
                            f"mc_{num:03d}",
                            [correct] + distractors[:3],
                        ),
                        "correct_answers": [correct],
                        "accepted_answers": [correct],
                        "explanation_template": topic["summary"],
                        "mistake_type": topic["mistake_type"],
                        "difficulty": 1 if num <= 4 else 2,
                        "llm_check_allowed": False,
                        "is_active": True,
                    }
                )
            for num, (prompt, correct, _distractors) in enumerate(topic["mc_gap_pairs"], start=1):
                exercises.append(
                    {
                        "exercise_id": f"{topic['topic_id']}_gap_{num:03d}",
                        "topic_id": topic["topic_id"],
                        "level": level.upper(),
                        "type": "fill_in_the_gap",
                        "prompt": prompt,
                        "options": [],
                        "correct_answers": [correct],
                        "accepted_answers": [correct],
                        "explanation_template": topic["summary"],
                        "mistake_type": topic["mistake_type"],
                        "difficulty": 1 if num <= 4 else 2,
                        "llm_check_allowed": False,
                        "is_active": True,
                    }
                )
            for num, (source_sentence, instruction, correct_answer) in enumerate(topic["transformations"], start=1):
                exercises.append(
                    {
                        "exercise_id": f"{topic['topic_id']}_trans_{num:03d}",
                        "topic_id": topic["topic_id"],
                        "level": level.upper(),
                        "type": "sentence_transformation",
                        "prompt": f"Rewrite: {source_sentence}",
                        "options": [],
                        "source_sentence": source_sentence,
                        "instruction": instruction,
                        "correct_answers": [correct_answer],
                        "accepted_answers": [correct_answer, correct_answer.rstrip(".")],
                        "explanation_template": topic["summary"],
                        "mistake_type": topic["mistake_type"],
                        "difficulty": 3,
                        "llm_check_allowed": True,
                        "is_active": True,
                    }
                )
            write_json(ROOT / "exercises" / f"{topic['topic_id']}.json", exercises)

        write_json(ROOT / "topics" / f"{level}.json", topic_rows)


if __name__ == "__main__":
    build_content()
    print("Grammar content generated.")
